apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-tag-binding
  namespace: devops-lab-cicd
spec:
  params:
    - name: git-repository-url
      value: $(body.repository.clone_url)
    - name: git-tag
      value: $(body.ref)

