apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: clone-build-push
  namespace: devops-lab-cicd
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
      description: The GitHub repository URL
    - name: image-reference
      type: string
      description: Full reference of the image to build and push
    - name: release-name
      type: string
      description: Helm release name
      default: devops-lab-app
    - name: helm-namespace
      type: string
      description: Namespace where Helm will deploy
      default: devops-lab-staging
  workspaces:
    - name: shared-data
    - name: docker-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: build-push
      runAfter:
        - fetch-source
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name: CONTEXT
          value: ./
        - name: DOCKERFILE
          value: ./Dockerfile
    - name: deploy-staging
      runAfter:
        - build-push
      taskRef:
        name: helm-deploy
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: RELEASE_NAME
          value: $(params.release-name)
        - name: NAMESPACE
          value: devops-lab-staging
        - name: VALUES_FILE
          value: cd/staging/values.yaml
    - name: deploy-pro
      runAfter:
        - deploy-staging
      taskRef:
        name: helm-deploy
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: RELEASE_NAME
          value: $(params.release-name)
        - name: NAMESPACE
          value: devops-lab-pro
        - name: VALUES_FILE
          value: cd/pro/values.yaml
